### PR TITLE
Support Laravel 8 and PHPUnit 9 updates

### PR DESCRIPTION
**Pull request by JayBizzle**
I have updated to allow support for Laravel 8.

Laravel 8 now requires PHPUnit 9. Some of the required changes to the tests are not backward compatible with PHPUnit 8, so I suggest releasing a new major version of this package `v5.0.0`.

This supersedes #71 which doesn't allow for the PHPUnit 9 update.

Thanks 👍

### CODE REVIEW

**Comment by JayBizzle** [comment]
Not sure why Travis hasn't been triggered for this PR?

**Comment by JayBizzle** [comment]
@ytake wondering if/when you may get a chance to review this PR. Thanks 👍

**Comment by ytake** [comment]
thanks 👍

**Comment by JayBizzle** [comment]
Awesome 👍🏻

**Pull request merged**
