### PR TITLE
view composer  name & path

### PR DESCRIPTION
**Pull request by ytake**

### CODE REVIEW

**Comment by JayBizzle** [comment]
Just one thing I have noticed after testing this out quickly.

If you have an include that uses a variable, the output will be incorrect.

e.g. if you have this in a template...
```smarty
{include file="Directory/Views/desktop/partials/filters/$filter.tpl"}
```

The output in Debugbar becomes...
```
Directory.Views.desktop.partials.filters.".((string)$_smarty_tpl->tpl_vars['filter']->value)."
```

**Comment by ytake** [comment]
solved!

**Comment by JayBizzle** [comment]
Great stuff!

I'll give it a test tomorrow when I'm back in the office.

**Comment by JayBizzle** [comment]
Just tested this locally. Looks good to go!

**Pull request merged**
